# Generated by Django 4.2.4 on 2023-08-30 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_alter_send_time'),
        ('client', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingListModel',
            new_name='MailingList',
        ),
    ]
