# Generated by Django 4.2.4 on 2023-08-30 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send', '0003_alter_send_time'),
        ('client', '0002_initial'),
        ('mailing', '0002_rename_mailinglistmodel_mailinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='client')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send.send', verbose_name='send')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
