# Generated by Django 4.2.4 on 2023-09-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_delete_mailinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылка'},
        ),
    ]
