# Generated by Django 4.2.3 on 2023-07-26 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('comment', models.TextField(verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Distription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема')),
                ('message', models.CharField(max_length=50, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Периодичность')),
            ],
            options={
                'verbose_name': 'Периодичность',
                'verbose_name_plural': 'Периоды',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_last', models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 17, 38, 625484, tzinfo=datetime.timezone.utc))),
                ('respounse', models.CharField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distription')),
            ],
        ),
        migrations.AddField(
            model_name='distription',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.message', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='distription',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.period', verbose_name='период'),
        ),
        migrations.AddField(
            model_name='distription',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.status', verbose_name='статус'),
        ),
    ]
