# Generated by Django 4.2.4 on 2023-08-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='status.status', verbose_name='статус'),
        ),
    ]
