# Generated by Django 4.2.4 on 2023-08-30 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время рассылки'),
        ),
    ]
