# Generated by Django 4.2.3 on 2023-08-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='params',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterField(
            model_name='params',
            name='status',
            field=models.ForeignKey(default='создана', on_delete=django.db.models.deletion.CASCADE, to='status.status', verbose_name='статус'),
        ),
    ]
