# Generated by Django 4.2.4 on 2023-09-05 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_last', models.DateTimeField(default=django.utils.timezone.now)),
                ('respounse', models.CharField(blank=True, null=True)),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send.send')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
