# Generated by Django 4.2.4 on 2023-08-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('send', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send.send'),
        ),
    ]
